### Arrays Pt. 2

In [27]:
import numpy as np

In [28]:
A = np.random.randint(1,11, size=(1,20))

In [29]:
A.size

20

In [30]:
print(A.shape)
print(A.size)
print(A.ndim)

(1, 20)
20
2


In [31]:
T = A.copy()

In [32]:
T.reshape(2,10)

array([[ 6,  7,  7,  7,  7,  7,  4,  5,  2,  2],
       [ 9,  8,  4,  6,  3,  8, 10,  7,  3,  9]])

In [43]:
A.resize(4,5)

In [44]:
A

array([[ 6,  7,  7,  7,  7],
       [ 7,  4,  5,  2,  2],
       [ 9,  8,  4,  6,  3],
       [ 8, 10,  7,  3,  9]])

In [45]:
#[:,:] is reshape=view or shallow copy

In [46]:
#copy() and .resize() makes a deep copy

In [48]:
S = A.flatten()

In [49]:
S[0] = 1

In [50]:
S

array([ 1,  7,  7,  7,  7,  7,  4,  5,  2,  2,  9,  8,  4,  6,  3,  8, 10,
        7,  3,  9])

In [51]:
A

array([[ 6,  7,  7,  7,  7],
       [ 7,  4,  5,  2,  2],
       [ 9,  8,  4,  6,  3],
       [ 8, 10,  7,  3,  9]])

In [52]:
S = A.ravel()

In [65]:
A = np.random.randint(1,11, size=(1,5))
B = np.random.randint(1,11, size=(4,5))

In [68]:
A

array([[6, 2, 1, 6, 6]])

In [69]:
B

array([[2, 4, 4, 7, 8],
       [8, 9, 1, 8, 7],
       [1, 2, 6, 1, 1],
       [3, 6, 7, 1, 8]])

In [70]:
np.hstack((A,B))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 1 and the array at index 1 has size 4

In [61]:
#A

In [62]:
#A.T #transpose: switches number of rows with number of columns

In [63]:
#B