### Arrays

In [4]:
import numpy as np

In [8]:
nums = np.array([10,10,45,32,54,67])

In [9]:
nums.dtype

dtype('int64')

In [10]:
nums

array([10, 10, 45, 32, 54, 67])

In [20]:
nums2 = np.random.randint(0,100, size=(10,5))

In [21]:
nums2

array([[60, 17, 13, 83, 96],
       [87, 47, 37, 82, 10],
       [40, 49, 25, 98, 32],
       [65, 31, 90, 33, 28],
       [58, 31, 79, 45, 81],
       [83, 37, 70, 67, 54],
       [23, 72, 34, 65, 64],
       [11, 20, 13, 13, 57],
       [53, 36, 91, 35, 66],
       [78, 63, 35, 80, 85]])

In [22]:
num2d = np.array([
    [10,10,45],
    [5,7,3],
    [65,76,96]
])

In [23]:
num2d.shape #output is (number of rows and columns)

(3, 3)

In [24]:
num2d.size #number of elements in the array

9

In [25]:
num2d.itemsize #number of bits in an element

8

In [27]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [28]:
np.linspace(0.0,1.0, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])