### PA5_WBG
---
**Author:** Ben Gierhart  
**Version:** 1.0  
**Semester:** Spring 2024 

This *notebook* contains my solution(s) to **PA5_WBG**

### Problem 1 — Language Translator

In [1]:
spanish_dictionary = {"chair": "silla",
    "man": "hombre",
    "woman": "mujer",
    "sun": "sol",
    "moon": "luna",
    "star": "estrella",
    "sky": "cielo",
    "car": "coche",
    "food": "comida",
    "city": "ciudad",
    "stop": "parada",
    "gas": "gasolina",
    "always": "siempre",
    "never": "nunca",
    "amazing": "maravilloso",
    "shelf": "estante",
    "book": "libro",
    "fox": "zorro",
    "keyboard": "teclado",
    "screen": "pantalla"
}

word = input("Enter a word to translate from English to Spanish (enter Q to stop):")
while word!="Q":
    if word in spanish_dictionary:
        print("The Spanish word for " + word + " is " + spanish_dictionary[word].upper() + ".")
        word = input("Enter a word to translate from English to Spanish (enter Q to stop):")
    else:
        print("The Spanish word for " + word.upper() + " is not in this dictionary.")
        word = input("Enter a word to translate from English to Spanish (enter Q to stop):")
if word=="Q":
    print("Done!")

Enter a word to translate from English to Spanish (enter Q to stop): couch


The Spanish word for COUCH is not in this dictionary.


Enter a word to translate from English to Spanish (enter Q to stop): man


The Spanish word for man is HOMBRE.


Enter a word to translate from English to Spanish (enter Q to stop): Q


Done!


### Problem 2 — Translating Morse Code

In [3]:
morse_code = {"A": ".–",
              "B": "–...",
              "C": "–.–.",
              "D": "–..",
              "E": ".",
              "F": "..–.",
              "G": "––.",
              "H": "....",
              "I": "..",
              "J": ".–––",
              "K": "–.–",
              "L": ".–..",
              "M": "––",
              "N": "–.",
              "O": "–––",
              "P": ".––.",
              "Q": "––.–",
              "R": ".–.",
              "S": "...",
              "T": "–",
              "U": "..–",
              "V": "...–",
              "W": ".––",
              "X": "_.._",
              "Y": "–.––",
              "Z": "––..",
              "0": "–––––",
              "1": ".––––",
              "2": "..–––",
              "3": "...––",
              "4": "....–",
              "5": ".....",
              "6": "–....",
              "7": "––...",
              "8": "–––..",
              "9": "––––."
}

def morse_code_translator():
    original_sentence = input('Type the sentence you would like translated into Morse Code. Use only uppercase letters and numbers. "q" to quit.')
    while original_sentence!="q":
        translated_text = ""
        for character in original_sentence:
            if character in morse_code:
                translated_text += morse_code[character]
            else:
                pass
        print(translated_text)
        original_sentence = input('Type the sentence you would like translated into Morse Code. Use only uppercase letters and numbers. "q" to quit.')
    if original_sentence=="q":
        print("Done!")

In [4]:
morse_code_translator()

Type the sentence you would like translated into Morse Code. Use only uppercase letters and numbers. "q" to quit. HELLO LILLY


......–...–..–––.–.....–...–..–.––


Type the sentence you would like translated into Morse Code. Use only uppercase letters and numbers. "q" to quit. Q


––.–


Type the sentence you would like translated into Morse Code. Use only uppercase letters and numbers. "q" to quit. q


Done!


### Problem 3 — Comparing Minors/Majors

In [14]:
Computer_Science_minor = {"CS130", "CS131", "CS215"}
Business_Administration_minor = {"BUSA103", "BUSA203", "BUSA301", "BUSA305", "ACCT101", "ECON110", "FINA315", "MATH117"}
Business_Analytics_minor = {"BUSA103", "BUSA245", "BUSA346", "CS150", "DS160", "DS300", "MATH117", "MATH205"}
Data_Science_major = {"BUSA103", "CS150", "MATH117", "DS160", "MATH205","BUSA245", "MATH215", "ECON111", "DS300", "BUSA346", "ECON410", "DS450"}

In [15]:
###i.###
Business_Administration_minor & Business_Analytics_minor

{'BUSA103', 'MATH117'}

In [16]:
###ii.###
Business_Administration_minor ^ Computer_Science_minor

{'ACCT101',
 'BUSA103',
 'BUSA203',
 'BUSA301',
 'BUSA305',
 'CS130',
 'CS131',
 'CS215',
 'ECON110',
 'FINA315',
 'MATH117'}

In [17]:
###iii.###
Business_Administration_minor - Business_Analytics_minor

{'ACCT101', 'BUSA203', 'BUSA301', 'BUSA305', 'ECON110', 'FINA315'}

In [18]:
###iv.###
Computer_Science_minor & Data_Science_major

set()

In [19]:
###v.###
Business_Analytics_minor - Data_Science_major

set()

### Problem 4 — Working with NumPy

In [20]:
import numpy as np

In [25]:
A1 = np.random.randint(1,21, size=(5,5))
A2 = np.random.randint(1,21, size=(5,5))

A1

array([[18,  2, 15,  6, 19],
       [ 4, 10,  4,  7, 14],
       [ 3, 19,  9, 12,  2],
       [19, 15,  4, 14,  3],
       [12, 15, 16,  1,  7]])

In [26]:
A2

array([[20, 16,  3, 12,  1],
       [16, 17, 19, 19, 19],
       [ 3,  7,  7,  1, 14],
       [ 6,  9,  2,  7,  2],
       [ 7,  7, 13, 15, 17]])

In [49]:
###a.###
matrix_product = np.dot(A1,A2)
print(matrix_product)

[[606 614 456 596 601]
 [392 423 426 501 502]
 [477 556 483 520 548]
 [737 734 437 660 439]
 [583 617 526 557 642]]


In [50]:
###b.###
det1 = np.linalg.det(A1)
det1

-788303.9999999992

In [51]:
det2 = np.linalg.det(A2)
det2

-74711.99999999999

In [52]:
inv1 = np.linalg.inv(A1)
inv1

array([[-4.51602427e-03, -9.43798332e-03, -5.50549027e-02,
         5.20915789e-02,  2.45387566e-02],
       [-6.10944509e-02,  5.63082263e-02, -2.57020134e-02,
         1.62310479e-02,  5.35986117e-02],
       [ 5.67103554e-02, -7.67064483e-02,  7.33790517e-02,
        -4.88073129e-02, -5.63234488e-04],
       [ 5.51360896e-02, -4.20751385e-02,  8.78950253e-02,
        -3.04451075e-05, -9.06046398e-02],
       [ 1.15818263e-03,  7.68586738e-02, -3.08244028e-02,
        -1.25167448e-02,  1.67448091e-04]])

In [53]:
inv2 = np.linalg.inv(A2)
inv2

array([[ 0.1146536 , -0.02224542,  0.01740015, -0.19624692,  0.02687654],
       [-0.06211854,  0.03995342,  0.03493415,  0.19061195, -0.09219403],
       [-0.07749759,  0.21209444, -0.07083199, -0.07958561, -0.1647928 ],
       [-0.0093827 , -0.05946836, -0.06539779,  0.09450958,  0.10975479],
       [ 0.04590963, -0.11700932,  0.09032016, -0.02021094,  0.11489453]])

In [54]:
###c.###
OneD_A1 = np.linspace(0.0,1.0, num=20)
OneD_A1

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [55]:
OneD_A2 = np.linspace(1.0,2.0, num=20)
OneD_A2

array([1.        , 1.05263158, 1.10526316, 1.15789474, 1.21052632,
       1.26315789, 1.31578947, 1.36842105, 1.42105263, 1.47368421,
       1.52631579, 1.57894737, 1.63157895, 1.68421053, 1.73684211,
       1.78947368, 1.84210526, 1.89473684, 1.94736842, 2.        ])

In [56]:
concatenated = np.concatenate((OneD_A1, OneD_A2))
concatenated

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ,
       1.        , 1.05263158, 1.10526316, 1.15789474, 1.21052632,
       1.26315789, 1.31578947, 1.36842105, 1.42105263, 1.47368421,
       1.52631579, 1.57894737, 1.63157895, 1.68421053, 1.73684211,
       1.78947368, 1.84210526, 1.89473684, 1.94736842, 2.        ])

In [57]:
concatenated.reshape(10,4)

array([[0.        , 0.05263158, 0.10526316, 0.15789474],
       [0.21052632, 0.26315789, 0.31578947, 0.36842105],
       [0.42105263, 0.47368421, 0.52631579, 0.57894737],
       [0.63157895, 0.68421053, 0.73684211, 0.78947368],
       [0.84210526, 0.89473684, 0.94736842, 1.        ],
       [1.        , 1.05263158, 1.10526316, 1.15789474],
       [1.21052632, 1.26315789, 1.31578947, 1.36842105],
       [1.42105263, 1.47368421, 1.52631579, 1.57894737],
       [1.63157895, 1.68421053, 1.73684211, 1.78947368],
       [1.84210526, 1.89473684, 1.94736842, 2.        ]])

In [7]:
world_premieres = {"A": "Starting on May 31, 2024 and continuing into Pride month, Actors Theatre of Louisville will partner with Drag Daddy Productions on the world premiere of Won't you be my May-bor? by Andrew Newton Schafflein and Eric Sharp, starring drag performer May O'Nays (Schafflein), and directed by Emily Tarquin, Actors Theatre's Executive Producer and Co-Director of Artistic Programming. In this production, May O'Nays portrays an escape room artist who has conquered every room but one—the elusive Mr. Rogers room. Unlike conventional escape rooms, this experience demands a shift in perspective as solving this puzzle will take patience, mindfulness, and deep listening. This interactive journey, inspired by the teachings of Mr. Rogers, will be a collective exploration of what it truly means to be a good neighbor. Won't you be my May-bor? will premiere in the Victor Jory Theater with a special sneak peek supported by the Fund for the Arts, before heading out to Owensboro, Hazard, and other communities throughout Kentucky.",
    "B": "On July 13, please join us at Alberta O. Jones Park for the world premiere of Who Killed Alberta Jones? by Larry Muhammad. In partnership with the Parks Alliance of Louisville, Actors Theatre of Louisville will present Redline Performing Arts' world-premiere production of this incredible play that tells the story of Alberta Odell Jones, the first Black woman to pass the bar in Kentucky. Jones was a prominent attorney and activist for voting rights, representing both vulnerable and prominent figures like Muhammad Ali. Jones' life was tragically cut short and her murder remains an unsolved case. Following the premiere in the park, the city's newest public green space, there will be several performances in the Victor Jory Theater in August."
}

def question1():
    selection = input("Please enter your the letter corresponding to your selection (enter Q to stop):")
    if selection in world_premieres:
        print(world_premieres[selection])
    
    else:
        print("That is not a valid selection")

In [11]:
question1()

Please enter your the letter corresponding to your selection (enter Q to stop): Q


Done!
